"""adding refresh token tables

Revision ID: 68ab3b81fbaf
Revises: 20acbb9f4efe
Create Date: 2026-03-01 01:01:51.051839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ab3b81fbaf'
down_revision: Union[str, Sequence[str], None] = '20acbb9f4efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
